export const GET_VEHICLE_UI_CONFIG_SUCCESS = 'GET_VEHICLE_UI_CONFIG_SUCCESS';
export const GET_VEHICLE_UI_CONFIG_FAILURE = 'GET_VEHICLE_UI_CONFIG_FAILURE';
export const TRY_GET_VEHICLE_UI_CONFIG = 'TRY_GET_VEHICLE_UI_CONFIG';
